In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

## **Importing Libraries**

In [ ]:
import pandas as pd
#import numpy as np
#import matplotlib.pyplot as plt
#import seaborn as sns
#plt.style.use('dark_background')

# **Reading CSV File**

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/data/india_all_restaurants_details.csv')

NameError: ignored

In [ ]:
df.head()

,Unnamed: 0,sno,zomato_url,name,city,area,rating,rating_count,telephone,cusine,cost_for_two,address,coordinates,timings,online_order,table_reservation,delivery_only,famous_food
0,0,0,https://www.zomato.com/ncr/sainik-food-pandav-...,Sainik Food,Delhi NCR,Pandav Nagar,3.2,21,011 22486474 +91 9717806814,North Indian,300,"C 4/1, Opposite Mother Dairy, Pandav Nagar, Ne...","28.6177324058,77.2848711535","{'Mon': '1pm – 4pm, 7pm – 10:30pm', 'Tue': '1p...",False,False,False,NaN
1,1,1,https://www.zomato.com/mumbai/kunals-creamery-...,Kunal's Creamery & Eatery,Mumbai,Ambernath,3.6,51,+91 9561356690 +91 9637537499,"Street Food, Chinese, Fast Food",500,"Shop 14, Trishul Shivdham Complex, Shiv Mandir...","19.2058869331,73.1842865422","{'Mon': '10am – 12midnight', 'Tue': '10am – 12...",False,False,False,Penne Pasta
2,2,2,https://www.zomato.com/ncr/brij-palace-restaur...,Brij Palace Restaurant,Delhi NCR,Jasola,0,0,+91 9891828106,North Indian,250,"4, Okhla Bus Stand, Jamia Nagar, Near, Jasola,...","28.5630343606,77.2912229598","{'Mon': '12noon – 4pm, 7pm – 12midnight', 'Tue...",False,False,False,"Chana Masala , Butter Naan , Paneer Bhujia , D..."
3,3,3,https://www.zomato.com/ncr/sahib-hotel-paharga...,Sahib Hotel,Delhi NCR,Paharganj,0,0,+91 9670005455,North Indian,300,"121, Amrit Kaur Market, Opposite New Delhi Rai...","28.6424106380,77.2182980552","{'Mon': '6am – 11:30pm, 12midnight – 1am', 'Tu...",False,False,False,NaN
4,4,4,https://www.zomato.com/kolkata/chunkys-shibpur...,Chunky's,Kolkata,Shibpur,3.0,78,+91 8442828284,"Italian, Pizza, Continental",500,"523, G.T Road, Howrah., Shibpur, Howrah","22.5777582163,88.3307084441","{'Mon': '12noon – 3am', 'Tue': '12noon – 3am',...",True,False,False,NaN

In [ ]:
df.tail()

,Unnamed: 0,sno,zomato_url,name,city,area,rating,rating_count,telephone,cusine,cost_for_two,address,coordinates,timings,online_order,table_reservation,delivery_only,famous_food
224515,83995,77966,https://www.zomato.com/dharamshala/norling-res...,Norling Restaurant,Dharamshala,Mcleodganj,3.2,4,+91 7018442293,"Chinese, Tibetan",400,"Dolma Chowk, Jogiwara Road, Mcleodganj, Dharam...","32.2371518771,76.3243285194","{'Mon': '8am – 10pm', 'Tue': '8am – 10pm', 'We...",False,False,False,NaN
224516,83996,77967,https://www.zomato.com/dharamshala/hobo-expres...,HOBO Express,Dharamshala,Shyam Nagar,NEW,0,+91 7833904972,"North Indian, Fast Food",200,"Rakkar, Shyam Nagar, Dharamshala","32.2003160000,76.3680210000","{'Mon': '10:30am – 9pm', 'Tue': '10:30am – 9pm...",True,False,False,NaN
224517,83997,77968,https://www.zomato.com/dharamshala/kalimpong-r...,Kalimpong Restaurant,Dharamshala,Mcleodganj,3.2,5,+91 9816743703,Fast Food,0,"Tipa Road, Mc Leod Ganj, Mcleodganj, Dharamshala","32.2389163722,76.3243710995","{'Mon': '11am – 11pm', 'Tue': '11am – 11pm', '...",False,False,False,NaN
224518,83998,77969,https://www.zomato.com/dharamshala/street-cafe...,Street Cafe,Dharamshala,Mcleodganj,3.2,4,+91 7888487723,"Chinese, North Indian",600,"Bhagsu Naag, Mcleodganj, Dharamshala","32.2437043281,76.3332106546","{'Mon': '11am – 10pm', 'Tue': '11am – 10pm', '...",False,False,False,NaN
224519,83999,77970,https://www.zomato.com/dharamshala/hotel-lhasa...,Hotel Lhasa,Dharamshala,Ram Nagar,NEW,0,+91 8219135267,"North Indian, Chinese, Fast Food, Beverages",250,"Main Square Mcleodganj, Kangra Town, Ram Nagar...","32.2417374000,76.3168537000","{'Mon': '7:30am – 10:30pm', 'Tue': '7:30am – 1...",True,False,False,NaN

In [ ]:
df.shape

(224520, 18)

In [ ]:
df.columns

Index(['Unnamed: 0', 'sno', 'zomato_url', 'name', 'city', 'area', 'rating',
       'rating_count', 'telephone', 'cusine', 'cost_for_two', 'address',
       'coordinates', 'timings', 'online_order', 'table_reservation',
       'delivery_only', 'famous_food'],
      dtype='object')

In [ ]:
df=df.drop(['zomato_url','address', 'telephone'],axis=1)
df.head()

,Unnamed: 0,sno,name,city,area,rating,rating_count,cusine,cost_for_two,coordinates,timings,online_order,table_reservation,delivery_only,famous_food
0,0,0,Sainik Food,Delhi NCR,Pandav Nagar,3.2,21,North Indian,300,"28.6177324058,77.2848711535","{'Mon': '1pm – 4pm, 7pm – 10:30pm', 'Tue': '1p...",False,False,False,NaN
1,1,1,Kunal's Creamery & Eatery,Mumbai,Ambernath,3.6,51,"Street Food, Chinese, Fast Food",500,"19.2058869331,73.1842865422","{'Mon': '10am – 12midnight', 'Tue': '10am – 12...",False,False,False,Penne Pasta
2,2,2,Brij Palace Restaurant,Delhi NCR,Jasola,0,0,North Indian,250,"28.5630343606,77.2912229598","{'Mon': '12noon – 4pm, 7pm – 12midnight', 'Tue...",False,False,False,"Chana Masala , Butter Naan , Paneer Bhujia , D..."
3,3,3,Sahib Hotel,Delhi NCR,Paharganj,0,0,North Indian,300,"28.6424106380,77.2182980552","{'Mon': '6am – 11:30pm, 12midnight – 1am', 'Tu...",False,False,False,NaN
4,4,4,Chunky's,Kolkata,Shibpur,3.0,78,"Italian, Pizza, Continental",500,"22.5777582163,88.3307084441","{'Mon': '12noon – 3am', 'Tue': '12noon – 3am',...",True,False,False,NaN

In [ ]:
df.info()

NameError: ignored

# **Dropping Duplicates**

In [ ]:
df.drop_duplicates(inplace=True)
df.shape

(224520, 15)

# **Cleaning rating column**

In [ ]:
df['rating'].unique()

NameError: ignored

# **Removing "NEW" and 'Nove' from Rate Column**

In [ ]:
def handlerate(value):
    if(value=='NEW' or value=='Nove'):
        return np.nan
    else:
        value = str(value).split('/')
        value = value[0]
        return float(value)

df['rating'] = df['rating'].apply(handlerate)
df['rating'].head()

NameError: ignored

In [ ]:
df.rating.isnull().sum()

0

In [ ]:
df['area'].unique()

array(['Pandav Nagar', 'Ambernath', 'Jasola', ..., 'Sangriya',
       'Gorkha Nagar', 'Jammu City'], dtype=object)

In [ ]:
df['cost_for_two'].unique()

array(['300', '500', '250', '200', '550', '150', '600', '650', '2,000',
       '1,400', '400', '450', '350', '100', '800', '700', '0', '850',
       '900', '750', '1,300', '3,000', '1,200', '1,500', '1,000', '1,100',
       '1,800', '4,000', '7,000', '1,600', '6,500', '2,500', '3,200',
       '50', '2,100', '3,300', '1,700', '3,500', '2,200', '2,700', '175',
       '2,400', '2,600', '1,050', '3,700', '2,300', '325', '950', '1,900',
       '3,100', '140', '1,150', '4,500', '5,000', '1,250', '1,850',
       '1,450', '360', '8,000', '80', '5,500', '1,550', '4,600', '1,750',
       '4,800', '120', '3,800', '220', '6,600', '135', '4,050', '3,600',
       '466', '480', '236', '2,800', '1,350', '6,000', '340', '198',
       '1,650', '4,200', '240', '3,900', '3,400', '580', '160', '838',
       '180', '233', '630', '3,650', '249', '125', '4,300', '2,650',
       '10,000', '280', '151', '130', '14,000', '70', '30,000', '481',
       '2,900', '199', '320', '1,260', '60', '248', '260', '15,000',
       '230', '505', '670', '40', '110', '420', '4,100', '15', '326',
       '20', '288', '306', '348', '1,190', '330', '1,950', '2,250', '730',
       '1,875', '620', '123', '999', '699', '75', '90', '294', '2', '380',
       '445', '208', '197', '592', '770', '440', '115', '598', '444',
       '470', '309', '414', '1,499', '282', '940', '195', '640', '7,500',
       '469', '210', '170', '312', '3,250', '1,020', '12,000', '30',
       '190', '2,501', '35', '520', '1000', '1200', '2000', '1300',
       '1100', '1400', '3000', '2500', '1800', '2200', '1600', '1500',
       '2300', '3200', '1700', '1900', '3500', '2100', '3800', '1650',
       '5000', '2700', '2250', '4500', '2400', 3000, 700, 2200, 1900, 900,
       1000, 500, 1700, 600, 800, 550, 750, 300, 400, 200, 150, 1200, 650,
       1300, 250, 1600, 100, 1800, 1500, 2000, 850, 450, 350, 3500, 1400,
       0, 2300, 2600, 2700, 1650, 1100, 3200, 2500, 495, 160, 1450, 2400,
       950, 2800, 139, 2100, 1050, 1150, 50, 3100, 4000, 4200, 240, 490,
       5500, 180, 110, 1250, 360, 60, 120, 3400, 1750, 1350, 230, 1550,
       730, 330, 299, 4500, 1230, 260, 280, 80, 170, 99, 440, 140, 480,
       70, 6000, 3600, 190, 220, 438, 501, 175, 404, 12000], dtype=object)

In [ ]:
def handlecomma(value):
  value=str(value)
  if ',' in value:
    value=value.replace(',','')
    return float(value)
  else:
    return float(value)

df['cost_for_two']=df['cost_for_two'].apply(handlecomma)
df['cost_for_two'].unique()

array([3.000e+02, 5.000e+02, 2.500e+02, 2.000e+02, 5.500e+02, 1.500e+02,
       6.000e+02, 6.500e+02, 2.000e+03, 1.400e+03, 4.000e+02, 4.500e+02,
       3.500e+02, 1.000e+02, 8.000e+02, 7.000e+02, 0.000e+00, 8.500e+02,
       9.000e+02, 7.500e+02, 1.300e+03, 3.000e+03, 1.200e+03, 1.500e+03,
       1.000e+03, 1.100e+03, 1.800e+03, 4.000e+03, 7.000e+03, 1.600e+03,
       6.500e+03, 2.500e+03, 3.200e+03, 5.000e+01, 2.100e+03, 3.300e+03,
       1.700e+03, 3.500e+03, 2.200e+03, 2.700e+03, 1.750e+02, 2.400e+03,
       2.600e+03, 1.050e+03, 3.700e+03, 2.300e+03, 3.250e+02, 9.500e+02,
       1.900e+03, 3.100e+03, 1.400e+02, 1.150e+03, 4.500e+03, 5.000e+03,
       1.250e+03, 1.850e+03, 1.450e+03, 3.600e+02, 8.000e+03, 8.000e+01,
       5.500e+03, 1.550e+03, 4.600e+03, 1.750e+03, 4.800e+03, 1.200e+02,
       3.800e+03, 2.200e+02, 6.600e+03, 1.350e+02, 4.050e+03, 3.600e+03,
       4.660e+02, 4.800e+02, 2.360e+02, 2.800e+03, 1.350e+03, 6.000e+03,
       3.400e+02, 1.980e+02, 1.650e+03, 4.200e+03, 2.400e+02, 3.900e+03,
       3.400e+03, 5.800e+02, 1.600e+02, 8.380e+02, 1.800e+02, 2.330e+02,
       6.300e+02, 3.650e+03, 2.490e+02, 1.250e+02, 4.300e+03, 2.650e+03,
       1.000e+04, 2.800e+02, 1.510e+02, 1.300e+02, 1.400e+04, 7.000e+01,
       3.000e+04, 4.810e+02, 2.900e+03, 1.990e+02, 3.200e+02, 1.260e+03,
       6.000e+01, 2.480e+02, 2.600e+02, 1.500e+04, 2.300e+02, 5.050e+02,
       6.700e+02, 4.000e+01, 1.100e+02, 4.200e+02, 4.100e+03, 1.500e+01,
       3.260e+02, 2.000e+01, 2.880e+02, 3.060e+02, 3.480e+02, 1.190e+03,
       3.300e+02, 1.950e+03, 2.250e+03, 7.300e+02, 1.875e+03, 6.200e+02,
       1.230e+02, 9.990e+02, 6.990e+02, 7.500e+01, 9.000e+01, 2.940e+02,
       2.000e+00, 3.800e+02, 4.450e+02, 2.080e+02, 1.970e+02, 5.920e+02,
       7.700e+02, 4.400e+02, 1.150e+02, 5.980e+02, 4.440e+02, 4.700e+02,
       3.090e+02, 4.140e+02, 1.499e+03, 2.820e+02, 9.400e+02, 1.950e+02,
       6.400e+02, 7.500e+03, 4.690e+02, 2.100e+02, 1.700e+02, 3.120e+02,
       3.250e+03, 1.020e+03, 1.200e+04, 3.000e+01, 1.900e+02, 2.501e+03,
       3.500e+01, 5.200e+02, 4.950e+02, 1.390e+02, 4.900e+02, 2.990e+02,
       1.230e+03, 9.900e+01, 4.380e+02, 5.010e+02, 4.040e+02])

In [ ]:
df['city'].value_counts()

Delhi NCR     38699
Mumbai        25692
Bengaluru     20283
Pune          15430
Hyderabad     12393
              ...
Darjeeling      132
Srinagar        128
Kharagpur        56
Tirupati         52
Neemrana         27
Name: city, Length: 83, dtype: int64

In [ ]:
city=df['city'].value_counts(ascending=False)

city_lessthan300=city[city<300]

def handle_city(value):
  if(value in city_lessthan300):
    return 'others'
  else:
    return value

df['city']=df['city'].apply(handle_city)
df['city'].value_counts()

Delhi NCR    38699
Mumbai       25692
Bengaluru    20283
Pune         15430
Hyderabad    12393
             ...
Guntur         355
Amravati       347
Vellore        339
Cuttack        331
Nainital       318
Name: city, Length: 68, dtype: int64